// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iofjtzdfwmwdukhizpyv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlvZmp0emRmd213ZHVraGl6cHl2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ5MzU1MjIsImV4cCI6MjA3MDUxMTUyMn0.kORsKV-rM5Wu3Kv8_DgH4_OXCdS42weuUA--AUhi6yg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});